### PR TITLE
Automated release to BioSimulators

### PR DESCRIPTION
**Pull request by jonrkarr**
To use the action, two "secrets" need to be added to this repository

1. Create a personal access token for agarny (or whichever user you want to use for the release)
   1. Go to https://github.com/settings/tokens
   2. Click "Generate new token"
   3. Select scope `repo`
   4. Click "Generate token"
   5. Copy the generated token
   
2. Create two secrets to store your username and the new token for your username:
   1. Go to https://github.com/biosimulations/Biosimulations/settings/secrets/actions
   2. Click "New repository secret"
   3. Add two secrets:
      `BIOSIMULATORS_GH_USERNAME`: `agarny` (or whichever user you choose)
      `BIOSIMULATORS_GH_TOKEN`: `<token>`

### CODE REVIEW

**Comment by agarny** [comment]
Hi @jonrkarr, I can't access https://github.com/biosimulations/Biosimulations/settings/secrets/actions, so I can't complete your second step.

**Comment by agarny** [comment]
Hmm... I am thinking that you probably meant https://github.com/opencor/docker/settings/secrets/actions?

**Comment by agarny** [comment]
This would make sense. So, ok, I have done your second step. Going to merge your PR and I understand that the next time I generate a new release of OpenCOR (and therefore of our docker), this will trigger a new release on BioSimulators.

**Comment by jonrkarr** [comment]
Yes https://github.com/opencor/docker/settings/secrets/actions. 

I blindly copied the link from one of my repos.

> I understand that the next time I generate a new release of OpenCOR (and therefore of our docker), this will trigger a new release on BioSimulators.

Yes! The action will automatically run when you tag a new release. If there are any issues with permissions I can help debug once the action runs.

**Comment by agarny** [comment]
I am hoping to generate a new version of OpenCOR in the next few days, so we will soon find out.

**Pull request merged**
